#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Stage 1: NTP by default; CL/OT are computed only when their weights are nonzero.
MODEL_NAME_OR_PATH="${MODEL_NAME_OR_PATH:-Qwen/Qwen2.5-0.5B}" \
CONFIG_FILE="${CONFIG_FILE:-$REPO_ROOT/configs/potsa_scheduler.yaml}" \
DATA_DIR="${DATA_DIR:-data/MT}" \
LANGUAGE_PAIRS="${LANGUAGE_PAIRS:-all}" \
OUTPUT_DIR="${OUTPUT_DIR:-outputs/stage1-multilingual-alignment}" \
DIRECTION="${DIRECTION:-both}" \
PRECISION="${PRECISION:-bf16}" \
PROMPT_FORMAT="${PROMPT_FORMAT:-plain}" \
ENABLE_THINKING="${ENABLE_THINKING:-false}" \
TRAINING_MODE="${TRAINING_MODE:-finetune}" \
ALIGN_LAYER="${ALIGN_LAYER:-}" \
CANDIDATE_LAYERS="${CANDIDATE_LAYERS:-}" \
REWARD_EMA_RHO="${REWARD_EMA_RHO:-0.1}" \
UCB_BETA="${UCB_BETA:-0.5}" \
LAYER_TEMPERATURE="${LAYER_TEMPERATURE:-1.0}" \
LAYER_WARMUP_STEPS="${LAYER_WARMUP_STEPS:-100}" \
FORCE_EACH_LAYER_ONCE="${FORCE_EACH_LAYER_ONCE:-true}" \
CONTRASTIVE_WEIGHT="${CONTRASTIVE_WEIGHT:-}" \
CONTRASTIVE_TEMPERATURE="${CONTRASTIVE_TEMPERATURE:-}" \
OT_WEIGHT="${OT_WEIGHT:-}" \
ATTENTION_MASS_WEIGHT="${ATTENTION_MASS_WEIGHT:-0.5}" \
LEARNING_RATE="${LEARNING_RATE:-2e-5}" \
EPOCHS="${EPOCHS:-3}" \
BATCH_SIZE="${BATCH_SIZE:-2}" \
GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS:-8}" \
SINKHORN_ITERATIONS="${SINKHORN_ITERATIONS:-20}" \
SINKHORN_EPSILON="${SINKHORN_EPSILON:-0.1}" \
SEED="${SEED:-42}" \
"$SCRIPT_DIR/run_train.sh"
