#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Stage 1: NTP by default; CL/OT are computed only when their weights are nonzero.
MODEL_NAME_OR_PATH="${MODEL_NAME_OR_PATH:-Qwen/Qwen2.5-0.5B}" \
DATA_DIR="${DATA_DIR:-data/MT}" \
LANGUAGE_PAIRS="${LANGUAGE_PAIRS:-all}" \
OUTPUT_DIR="${OUTPUT_DIR:-outputs/stage1-multilingual-alignment}" \
DIRECTION="${DIRECTION:-both}" \
PRECISION="${PRECISION:-bf16}" \
ALIGN_LAYER="${ALIGN_LAYER:--1}" \
CONTRASTIVE_WEIGHT="${CONTRASTIVE_WEIGHT:-0.0}" \
CONTRASTIVE_TEMPERATURE="${CONTRASTIVE_TEMPERATURE:-0.07}" \
OT_WEIGHT="${OT_WEIGHT:-0.0}" \
ATTENTION_MASS_WEIGHT="${ATTENTION_MASS_WEIGHT:-0.5}" \
LEARNING_RATE="${LEARNING_RATE:-2e-5}" \
EPOCHS="${EPOCHS:-3}" \
BATCH_SIZE="${BATCH_SIZE:-2}" \
GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS:-8}" \
SINKHORN_ITERATIONS="${SINKHORN_ITERATIONS:-20}" \
SINKHORN_EPSILON="${SINKHORN_EPSILON:-0.1}" \
SEED="${SEED:-42}" \
"$SCRIPT_DIR/run_train.sh"
